accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
]

adminapp/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'adminapp'

urlpatterns = [
    path('home', views.home, name='home'),
    path('addbook', views.addbook, name='addbook'),
    path('updatebook', views.updatebook, name='updatebook'),
    path('deletebook', views.deletebook, name='deletebook'),
]

libraryproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('adminapp/', include('adminapp.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models

# Create your models here.
class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, **extra_fields)

class User(AbstractUser):
    username = None
    is_staff = None
    is_superuser = None
    is_active = None
    email = models.EmailField(('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

adminapp/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    book_name = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return self.book_name

accounts/views.py
from django.contrib.auth import models
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from .models import User
from django.contrib.auth.decorators import login_required


# Create your views here.
def register(request):
    if request.method == 'POST':
        #Get form values
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        #Password validation
        if password == password2:
            if User.objects.filter(email=email).exists():
                return redirect('register')
            else:
                #User creation
                first_name = first_name.capitalize()
                last_name = last_name.capitalize()
                user = User.objects.create_user(first_name=first_name, last_name=last_name, email=email,
                password=password)
                return redirect('register')
        else:
            return redirect('register')
    else:
        return render(request, 'register.html')

def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = auth.authenticate(email=email, password=password)
        #Credentials match
        if user is not None:
            auth.login(request, user)
            
            return redirect('adminapp/home')
        else:
            messages.error(request, 'Invalid credentials')
            return redirect('/')
    else:
        if request.user.is_authenticated:
            return redirect('adminapp/home')
        else:
            return render(request, 'login.html')

@login_required(login_url="/")
def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('/')

adminapp/views.py
from django.shortcuts import render, redirect
from .models import Book

# Create your views here.
def home(request):
    books_data = Book.objects.all()
    context = {'books_data': books_data}
    return render(request, 'home.html', context=context)

def addbook(request):
    if request.method == 'POST':
        #Get form values
        book_name = request.POST['book_name']
        author = request.POST['author']
        quantity = request.POST['quantity']

        if Book.objects.filter(book_name=book_name, author=author).exists():
            print('Book already exist')
            return redirect('adminapp:addbook')
        else:
            book = Book(book_name=book_name, author=author, quantity=quantity)
            book.save()
            print('Book added successfully')
            return redirect('adminapp:home')
    else:
        return render(request, 'addbook.html')

def updatebook(request):
    books_data = Book.objects.all()
    context = {'books_data': books_data}

    #Fetch book record
    if request.method == 'GET':
        id = request.GET['id']
        book = Book.objects.get(id=id)
        context = {'book': book}
        return render(request, 'updatebook.html', context=context)
    elif request.method == 'POST': #update record
        book_name = request.POST['book_name']
        author = request.POST['author']
        quantity = request.POST['quantity']
        if book_name != '' and book_name != book.book_name:
            book.book_name = book_name
            book.save()

        if author != '' and author != book.author:
            book.author = author
            book.save()

        if quantity != 0 and quantity != book.quantity:
            book.quantity = quantity
            book.save()
        else:
            return redirect('adminapp:home')
    else: 
        return render(request, 'updatebook.html', context=context)

def deletebook(request):
    if request.method == 'POST':
        id = request.POST['id']
        if Book.objects.filter(id=id).exists():
            book = Book.objects.get(id=id)
            book.delete()
            print('Record deleted')
            return redirect('adminapp:home')
        else:
            print('Incorrect ID')
            return redirect('adminapp:deletebook')
    else:    
        return render(request, 'deletebook.html')

templates/addbook.html
{% extends 'base.html' %}

{% block title %}Add Book{% endblock %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

{% block body %}
<div class="container">
    <h4 class="pt-4 text-center">ADD NEW BOOK</h4>
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-8 pt-4 pb-4 col-xl-6">
            <div class="card rounded-3">
            <div class="card-body p-4 p-md-5">
    
                <form class="px-md-2" method="POST" action="{% url 'adminapp:addbook' %}" >
    
                {% csrf_token %}
    
                <div class="form-outline mb-4">
                    <label class="form-label" for="book_name">Book Name</label>
                    <input type="text" id="book_name" name="book_name" class="form-control" required />
                </div>
                <div class="form-outline mb-4">
                    <label class="form-label" for="author">Author</label>
                    <input type="text" name="author" id="author" class="form-control" required />
                </div>
                <div class="form-outline mb-4">
                    <label class="form-label" for="quantity">Quantity</label>
                    <input type="number" name="quantity" id="quantity" min="1" class="form-control" required />
                </div>
    
                <button type="submit" class="btn btn-success btn-lg mb-1">Add</button>
    
                </form>
    
            </div>
            </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="bg-light">
    {% block navbar %}{% endblock %}
    <div class="container-fluid">
        {% block body %}{% endblock %}
    </div>

    <!-- Bootstrap JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

templates/deletebook.html
{% extends 'base.html' %}

{% block title %}Delete Book{% endblock %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

{% block body %}
<div class="container">
    <h4 class="pt-4 text-center">DELETE EXISTING BOOK RECORD</h4>
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-8 pt-4 col-xl-6">
            <div class="card rounded-3">
            <div class="card-body p-4 p-md-5">
    
                <form class="px-md-2" method="POST" action="{% url 'adminapp:deletebook' %}" >
    
                {% csrf_token %}
    
                <div class="form-outline mb-4">
                    <label class="form-label" for="id">Book ID</label>
                    <input type="number" name="id" id="id" min="1" class="form-control" required />
                </div>
    
                <button type="submit" class="btn btn-success btn-lg mb-1">Delete Record</button>
    
                </form>
    
            </div>
            </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

{% block body %}
<div class="container text-center">
    <h4 class="pt-4 pb-4">LIST OF ALL BOOKS</h4>
    <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Book Name</th>
            <th scope="col">Author</th>
            <th scope="col">Qty</th>
          </tr>
        </thead>
        <tbody>
          {%for book in books_data %}
          <tr>
            <th scope="row">{{book.id}}</th>
            <td>{{book.book_name}}</td>
            <td>{{book.author}}</td>
            <td>{{book.quantity}}</td>
          </tr>
          {%endfor%}
        </tbody>
    </table>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}Registration{% endblock %}

{% block body %}
<section class="h-100 h-custom" style="background-color: #8fc4b7;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-8 pt-5 pb-5 col-xl-6">
        <div class="card rounded-3">
          <div class="card-body p-4 p-md-5">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Admin Login Page</h3>

            <form class="px-md-2" method="POST" action="{% url 'login' %}">

              {% csrf_token %}

              <div class="form-outline mb-4">
                  <label class="form-label" for="email">Email</label>
                  <input type="email" id="email" name="email" class="form-control" />
              </div>
              <div class="form-outline mb-4">
                  <label class="form-label" for="password">Password</label>
                  <input type="password" name="password" id="password" class="form-control" />
              </div>

              <button type="submit" class="btn btn-success btn-lg mb-1">Login</button>

            </form>

            <h6 class="pt-4">Not registered yet? <a href="register">Register here</a></h6>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav ml-auto text-center">
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" href="home">List All Books</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'addbook' %}active{% endif %}" href="addbook">Add New Book</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'updatebook' %}active{% endif %}" href="updatebook">Update Book</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'deletebook' %}active{% endif %}" href="deletebook">Delete Book</a>
            </li>
        </ul>
        <div class="collapse navbar-collapse justify-content-end" id="navbarScroll">
            <form class="d-flex" method="POST" action="{% url 'logout' %}">
                
                {% csrf_token %}
                
                <button class="btn btn-outline-success" type="submit">Logout</button>
            </form>
        </div>
    </div>
</nav>

templates/register.html
{% extends 'base.html' %}

{% block title %}Registration{% endblock %}

{% block body %}
<section class="h-100 h-custom" style="background-color: #8fc4b7;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-8 col-xl-6">
          <div class="card rounded-3">
            <div class="card-body p-4 p-md-5">
              <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Admin Registeration Page</h3>
  
              <form class="px-md-2" method="POST" action="{% url 'register' %}">
                
                {% csrf_token %}
  
                <div class="form-outline mb-4">
                    <label class="form-label" for="first_name">First Name</label>
                    <input type="text" id="first_name" name="first_name" class="form-control" />
                </div>
                <div class="form-outline mb-4">
                    <label class="form-label" for="last_name">Last Name</label>
                    <input type="text" id="last_name" name="last_name" class="form-control" />
                </div>
                <div class="form-outline mb-4">
                    <label class="form-label" for="email">Email</label>
                    <input type="email" id="email" name="email" class="form-control" />
                </div>
                <div class="form-outline mb-4">
                    <label class="form-label" for="password">Password</label>
                    <input type="password" id="password" name="password" class="form-control" />
                </div>
                <div class="form-outline mb-4">
                    <label class="form-label" for="password2">Confirm Password</label>
                    <input type="password" id="password2" name="password2" class="form-control" />
                </div>
  
                <button type="submit" class="btn btn-success btn-lg mb-1">Submit</button>
  
              </form>

              <h6 class="pt-4">Already have an account? <a href="/">Sign in</a></h6>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/updatebook.html
{% extends 'base.html' %}

{% block title %}Update Book{% endblock %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

{% block body %}
<div class="container">
    <h4 class="pt-4 text-center">UPDATE EXISTING BOOK RECORD</h4>
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-8 pt-4 pb-4 col-xl-6">
            <div class="card rounded-3">
            <div class="card-body p-4 p-md-5">
                <form class="px-md-2" method="GET" action="{% url 'adminapp:updatebook' %}" >
    
                    {% csrf_token %}
                
                    <div class="form-outline mb-4">
                        <label class="form-label" for="book_name">Select Book ID</label>
                        <select name="id" class="form-select" required>
                            <option value="">--Select--</option>
                            {% for book in books_data %}
                            <option value="{{book.id}}">{{book.id}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success btn-lg mb-1">Fetch Details</button>
                </form>

                <form class="px-md-2" method="POST" action="{% url 'adminapp:updatebook' %}" >
    
                    {% csrf_token %}
                    {% for i in book %}
                    <div class="form-outline mb-4">
                        <label class="form-label" for="book_name">Book Name</label>
                        <input type="text" id="book_name" value="{{i.book_name}}" name="book_name" class="form-control" required />
                    </div>
                    <div class="form-outline mb-4">
                        <label class="form-label" for="author">Author</label>
                        <input type="text" name="author" id="author" value="{{ i.author }}" class="form-control" required />
                    </div>
                    <div class="form-outline mb-4">
                        <label class="form-label" for="quantity">Quantity</label>
                        <input type="number" name="quantity" id="quantity" min="1" value="{{i.quantity}}" class="form-control" required />
                    </div>
                    {% endfor %}
    
                    <button type="submit" class="btn btn-success btn-lg mb-1">Update</button>
    
                </form>
    
            </div>
            </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}